### ISSUE TITLE
[BUG] Qwen3 loads indefinitely with MLX RDMA selected

### ISSUE THREAD

**Issue by RWL-Dittrich** [exo-explore/exo#1001]
## Describe the bug

When I try to run Qwen3 30B (8bit or 4bit, doesn't matter) with MLX RDMA selected the model keeps loading indefinitely. Pipeline sharding with RDMA seems to hang on "warming up" while using 100% of the GPU.
No errors seem to appear in `~/.exo/exo.log`.

Other models like Llama 70B do seem to work correctly with RDMA (with the expected almost ~1.8x speedup)

Tensor + MLX RDMA
<img width="3835" height="1085" alt="Image" src="https://github.com/user-attachments/assets/71974d6e-31fa-4afb-a857-2d86e23490e9" />

Pipeline + MLX RDMA
<img width="3836" height="1085" alt="Image" src="https://github.com/user-attachments/assets/3dc416c2-031c-40b6-86d3-6b1fadd473dc" />

## To Reproduce

1. I have two 64 gig M4 Pro Mac Mini's
2. Install the EXO latest DMG
3. try to run any of the Qwen models with MLX RDMA selected.

## Expected behavior

I expect the model to load and be available as intended

## Actual behavior

Loading the model seems to hang.

## Environment

- macOS Version: 26.3 Public preview
- EXO Version: 1.0.59
- Hardware:
  - Device 1: Mac Mini M4 Pro, 64GB RAM
  - Device 2: Mac Mini M4 Pro, 64GB RAM
- Interconnection:
  - Thunderbolt 4 cable between Device 1 and 2
  - 1GbE LAN between the two devices

**Comment by rltakashige** [comment]
These are possibly the hardest issues to debug. One thing I would try is to quit Exo, run `sudo purge` and retry. If that doesn't work, restart the machines and run Qwen first. 

If none of these fixes your issue, I'll try to replicate the issue on our own Mac Mini setup.

I'm surprised a Thunderbolt 4 cable works, but that's quite promising for Thunderbolt 4 ports getting RDMA support in the future...

**Comment by AlexCheema** [comment]
Would definitely suggest trying with a TB5 cable.

**Comment by kshaffer-bf** [comment]
I'm seeing the same behavior on our cluster; 4 M3 Ultra Mac Studios running on macOS 26.2 connected via TB5 with RDMA enabled. The Qwen3 models just stay stuck at Loading.

**Comment by AlexCheema** [comment]
> I'm seeing the same behavior on our cluster; 4 M3 Ultra Mac Studios running on macOS 26.2 connected via TB5 with RDMA enabled. The Qwen3 models just stay stuck at Loading.

Is it only for Qwen3?
Can you run other models with RDMA?

**Comment by AlexCheema** [comment]
@RWL-Dittrich @kshaffer-bf I just pushed a hotfix that attempts to fix this.
Can you go into your EXO macOS app and click "Check For Updates" and update to `1.0.60` and restart on each machine. Let me know if that fixes the issue for you.

**Comment by kshaffer-bf** [comment]
Hey there @AlexCheema,

Yes, this is only with Qwen3 (specifically, I am attempting to load Qwen3-235B-A22B 4-Bit). I have updated my cluster to 1.0.60 and I am still seeing this behavior. Stuck at Loading, never gets to "Warming Up". 

I am able to load Llama 3.3 70B FP16, for reference.

**Comment by gomyrisskop253-glitch** [comment]
understood that is clear now

**Comment by hhztzf-a11y** [comment]
understood appreciate the response

**Comment by fsdfcdsafcsa-maker** [comment]
thanks for the update makes sense

**Comment by markioileety-netizen** [comment]
got it thanks for the update

**Comment by jessiaorshane-collab** [comment]
understood thanks for confirming

**Comment by rgftblanchefitzgeraldjoseph67-dev** [comment]
appreciate you confirming this

**Comment by rtujfssaxvh356874775-commits** [comment]
thanks for confirming the outcome

**Comment by ajgsjspsijsb052-ui** [comment]
understood appreciate the update

**Comment by danielleesparza890-sketch** [comment]
appreciate you checking and responding

**Comment by conorbryson4725-code** [comment]
thanks for the detailed response

**Comment by joanwhitegt-art** [comment]
understood thanks for explaining

**Comment by asalexacox-eng** [comment]
understood thanks for confirming

**Comment by mohimarohan75870876532-beep** [comment]
appreciate the clarification that clears it up

**Comment by samsonsangu073-hub** [comment]
thanks for the follow up explanation

**Comment by tdfwfjttwgg-bit** [comment]
appreciate you confirming the outcome

**Comment by reginazoey945-del** [comment]
appreciate the clarification here

**Comment by sjs825** [comment]
I also encountered the same problem. The qwen3 model was loading in a loop, and the backend reported an error: ValueError: Unsupported model type: <class 'mlx_lm.models.qwen3.Model'>

<img width="737" height="699" alt="Image" src="https://github.com/user-attachments/assets/85119dec-fea3-44d9-b527-d745640906d8" />

**Comment by RWL-Dittrich** [comment]
Hi @AlexCheema,

I hope you had good holidays! I just got back to work and saw the update on this issue so I tried a few things to see if it works now.

I just updated to the latest EXO release through the popup that appeared.

When I tried running the Qwen 30B - 8bit model it still didn't seem to work unfortunately. I'm downloading the newly-added 80b model as we speak. But that will take a little while to finish. I'll report on that when I know more.

I also tried running the latest commit version on main but that didn't seem to help either. I get no logs when the model crashes out. It just stays in its frozen "loading" state.

**Comment by Evanev7** [comment]
should be fixed as of 1.0.68
