### ISSUE TITLE
Networking issue on cluster of two raspberry pis

### ISSUE THREAD

**Issue by dtnewman** [exo-explore/exo#308]
I am running this on a cluster of two raspberry pis. Note that I am on the branch from [this PR](https://github.com/exo-explore/exo/pull/139), since I get the "clang issue" using tinygrad.

when submitting a request using the Llama 3.1B model, i get this error on Pi 1:
```
Task exception was never retrieved
future: <Task finished name='Task-431' coro=<UDPDiscovery.on_listen_message() done, defined at 
/home/daniel/code/exo_temp/exo-daniel/exo/networking/udp/udp_discovery.py:118> exception=KeyError('302ae018-5202-441c-bd2e-a4ba4f19ea49')>
Traceback (most recent call last):
  File "/home/daniel/code/exo_temp/exo-daniel/exo/networking/udp/udp_discovery.py", line 162, in on_listen_message
    self.known_peers[peer_id] = (self.known_peers[peer_id][0], self.known_peers[peer_id][1], time.time(), peer_prio)
                                 ~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: '302ae018-5202-441c-bd2e-a4ba4f19ea49'
Error in cleanup peers: dictionary changed size during iteration
Traceback (most recent call last):
  File "/home/daniel/code/exo_temp/exo-daniel/exo/networking/udp/udp_discovery.py", line 174, in task_cleanup_peers
    for peer_id, (peer_handle, connected_at, last_seen, prio) in self.known_peers.items():
RuntimeError: dictionary changed size during iteration
```

And this one on Pi 2:
```
Error in cleanup peers: dictionary changed size during iteration
Traceback (most recent call last):
  File "/home/daniel/code/exo_temp/exo-daniel/exo/networking/udp/udp_discovery.py", line 174, in task_cleanup_peers
    for peer_id, (peer_handle, connected_at, last_seen, prio) in self.known_peers.items():
RuntimeError: dictionary changed size during iteration
```

I haven't pinned it down yet, but it seems like something is failing in the `health_check` function in `exo/networking/grpc/grpc_peer_handle.py`.

**Comment by AlexCheema** [comment]
Thanks for the detailed report. Can you test that this is fixed now after #309  @dtnewman

**Comment by dtnewman** [comment]
It's still breaking, but I'm getting a _different_ error now on the Pis.

```
Error broadcasting result to 302ae018-5202-441c-bd2e-a4ba4f19ea49: <AioRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Unexpected <class 'AttributeError'>: 'NoneType' object has no attribute 'decode'"
        debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-10-07T13:33:23.263493652-04:00", grpc_status:2, 
grpc_message:"Unexpected <class \'AttributeError\'>: \'NoneType\' object has no attribute \'decode\'"}"
>
Traceback (most recent call last):
  File "/home/daniel/code/exo_temp/exo-daniel/exo/orchestration/standard_node.py", line 407, in send_result_to_peer
    await asyncio.wait_for(peer.send_result(request_id, result, is_finished), timeout=15.0)
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/home/daniel/code/exo_temp/exo-daniel/exo/networking/grpc/grpc_peer_handle.py", line 132, in send_result
    await self.stub.SendResult(request)
  File "/home/daniel/.virtualenvs/exo_venv/lib/python3.12/site-packages/grpc/aio/_call.py", line 318, in __await__
    raise _create_rpc_error(
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Unexpected <class 'AttributeError'>: 'NoneType' object has no attribute 'decode'"
        debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-10-07T13:33:23.263493652-04:00", grpc_status:2, 
grpc_message:"Unexpected <class \'AttributeError\'>: \'NoneType\' object has no attribute \'decode\'"}"
>
Task exception was never retrieved
future: <Task finished name='Task-319' coro=<UDPDiscovery.on_listen_message() done, defined at 
/home/daniel/code/exo_temp/exo-daniel/exo/networking/udp/udp_discovery.py:118> exception=KeyError('302ae018-5202-441c-bd2e-a4ba4f19ea49')>
Traceback (most recent call last):
  File "/home/daniel/code/exo_temp/exo-daniel/exo/networking/udp/udp_discovery.py", line 162, in on_listen_message
    self.known_peers[peer_id] = (self.known_peers[peer_id][0], self.known_peers[peer_id][1], time.time(), peer_prio)
                                 ~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: '302ae018-5202-441c-bd2e-a4ba4f19ea49'
```

**Comment by AlexCheema** [comment]
Reopening

**Comment by AlexCheema** [comment]
```
Error broadcasting result to 302ae018-5202-441c-bd2e-a4ba4f19ea49: <AioRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Unexpected <class 'AttributeError'>: 'NoneType' object has no attribute 'decode'"
        debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-10-07T13:33:23.263493652-04:00", grpc_status:2, 
grpc_message:"Unexpected <class \'AttributeError\'>: \'NoneType\' object has no attribute \'decode\'"}"
>
```

This error looks like something to do with the PyTorch inference engine so should go in #139 

---


```
future: <Task finished name='Task-319' coro=<UDPDiscovery.on_listen_message() done, defined at 
/home/daniel/code/exo_temp/exo-daniel/exo/networking/udp/udp_discovery.py:118> exception=KeyError('302ae018-5202-441c-bd2e-a4ba4f19ea49')>
Traceback (most recent call last):
  File "/home/daniel/code/exo_temp/exo-daniel/exo/networking/udp/udp_discovery.py", line 162, in on_listen_message
    self.known_peers[peer_id] = (self.known_peers[peer_id][0], self.known_peers[peer_id][1], time.time(), peer_prio)
                                 ~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: '302ae018-5202-441c-bd2e-a4ba4f19ea49'
```

This error was a race condition that is fixed in #310

**Comment by AlexCheema** [comment]
Is this working for you now @dtnewman

**Comment by dtnewman** [comment]
I'm still getting failures on the healthcheck. Adjusting the timeout from 5 to 15 does seem to help though.

```
  File "/home/daniel/.virtualenvs/exo_venv/lib/python3.12/site-packages/grpc/aio/_call.py", line 316, in __await__
    raise asyncio.CancelledError()
asyncio.exceptions.CancelledError
Peer 302ae018-5202-441c-bd2e-a4ba4f19ea49 at 192.168.86.34:55998 is not healthy. Removing.
Health check failed for 302ae018-5202-441c-bd2e-a4ba4f19ea49@192.168.86.34:55998.
Traceback (most recent call last):
  File "/home/daniel/code/exo_temp/exo-daniel/exo/networking/grpc/grpc_peer_handle.py", line 56, in health_check
    response = await asyncio.wait_for(self.stub.HealthCheck(request), timeout=5)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
```

![image](https://github.com/user-attachments/assets/73361599-421b-4637-bde1-ff0abb310243)

**Comment by AlexCheema** [comment]
> I'm still getting failures on the healthcheck. Adjusting the timeout from 5 to 15 does seem to help though.
> 
> ```
>   File "/home/daniel/.virtualenvs/exo_venv/lib/python3.12/site-packages/grpc/aio/_call.py", line 316, in __await__
>     raise asyncio.CancelledError()
> asyncio.exceptions.CancelledError
> Peer 302ae018-5202-441c-bd2e-a4ba4f19ea49 at 192.168.86.34:55998 is not healthy. Removing.
> Health check failed for 302ae018-5202-441c-bd2e-a4ba4f19ea49@192.168.86.34:55998.
> Traceback (most recent call last):
>   File "/home/daniel/code/exo_temp/exo-daniel/exo/networking/grpc/grpc_peer_handle.py", line 56, in health_check
>     response = await asyncio.wait_for(self.stub.HealthCheck(request), timeout=5)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
>     return await fut
>            ^^^^^^^^^
> ```
> 
> Here's an image of it working with two Pis: ![image](https://private-user-images.githubusercontent.com/3669803/374319850-73361599-421b-4637-bde1-ff0abb310243.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMzU1MjIsIm5iZiI6MTcyODMzNTIyMiwicGF0aCI6Ii8zNjY5ODAzLzM3NDMxOTg1MC03MzM2MTU5OS00MjFiLTQ2MzctYmRlMS1mZjBhYmIzMTAyNDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDdUMjEwNzAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWE2OGRlYTNjMWIxNWYyNzU3Y2VmYTc0OWEzYzIxZGM1OWJhZWIzMjBjODJjNjY1ZDE2ZGVjNmY0M2ExNDdlNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.eDuxWqPGDvE8_eYfaqGXn6AjlFkM-i1FvbhtgFBDxYI)

It might be because the PyTorch inference engine is blocking. The other `InferenceEngine` implementations run on all the blocking operations on a `ThreadPoolExecutor`, although I'm not sure this is the best solution for PyTorch - there may be a more "torch-native" way of doing asynchronous execution.
