### ISSUE TITLE
Failed to build installable wheels for some pyproject.toml based projects

### ISSUE THREAD

**Issue by maruwtc** [exo-explore/exo#550]
Environment:
- MacBook Air M2, 2022 16GB
- MacOS Version 15.2 Beta (24C5089c)
- Python 3.13.1
 
Error Log:
```
Building wheels for collected packages: exo, sentencepiece
  Building editable for exo (pyproject.toml) ... done
  Created wheel for exo: filename=exo-0.0.1-0.editable-py3-none-any.whl size=15497 sha256=dee8f03691838da17438f57d60bf270676648c4230d6aa65c72c3e5464254570
  Stored in directory: /private/var/folders/1b/6lfy9pzd0b58gbpvphcgmj6h0000gn/T/pip-ephem-wheel-cache-k6m4kfou/wheels/c1/5e/86/de3353864d7fe5f673e943bcb54e66446a47269a0283baa227
  Building wheel for sentencepiece (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for sentencepiece (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [106 lines of output]
      /private/var/folders/1b/6lfy9pzd0b58gbpvphcgmj6h0000gn/T/pip-build-env-dazivlui/overlay/lib/python3.13/site-packages/setuptools/_distutils/dist.py:261: UserWarning: Unknown distribution option: 'test_suite'
        warnings.warn(msg)
      running bdist_wheel
      running build
      running build_py
      creating build/lib.macosx-10.13-universal2-cpython-313/sentencepiece
      copying src/sentencepiece/__init__.py -> build/lib.macosx-10.13-universal2-cpython-313/sentencepiece
      copying src/sentencepiece/_version.py -> build/lib.macosx-10.13-universal2-cpython-313/sentencepiece
      copying src/sentencepiece/sentencepiece_model_pb2.py -> build/lib.macosx-10.13-universal2-cpython-313/sentencepiece
      copying src/sentencepiece/sentencepiece_pb2.py -> build/lib.macosx-10.13-universal2-cpython-313/sentencepiece
      running build_ext
      /bin/sh: pkg-config: command not found
      ./build_bundled.sh: line 21: cmake: command not found
      ./build_bundled.sh: line 22: nproc: command not found
      ./build_bundled.sh: line 22: cmake: command not found
      Traceback (most recent call last):
        File "/Users/chriswong/Documents/repo/exo/.venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "/Users/chriswong/Documents/repo/exo/.venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/chriswong/Documents/repo/exo/.venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                              metadata_directory)
                                              ^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/1b/6lfy9pzd0b58gbpvphcgmj6h0000gn/T/pip-build-env-dazivlui/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 438, in build_wheel
          return _build(['bdist_wheel', '--dist-info-dir', str(metadata_directory)])
        File "/private/var/folders/1b/6lfy9pzd0b58gbpvphcgmj6h0000gn/T/pip-build-env-dazivlui/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 426, in _build
          return self._build_with_temp_dir(
                 ~~~~~~~~~~~~~~~~~~~~~~~~~^
              cmd,
              ^^^^
          ...<3 lines>...
              self._arbitrary_args(config_settings),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          )
          ^
        File "/private/var/folders/1b/6lfy9pzd0b58gbpvphcgmj6h0000gn/T/pip-build-env-dazivlui/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 407, in _build_with_temp_dir
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/private/var/folders/1b/6lfy9pzd0b58gbpvphcgmj6h0000gn/T/pip-build-env-dazivlui/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/1b/6lfy9pzd0b58gbpvphcgmj6h0000gn/T/pip-build-env-dazivlui/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 169, in <module>
        File "/private/var/folders/1b/6lfy9pzd0b58gbpvphcgmj6h0000gn/T/pip-build-env-dazivlui/overlay/lib/python3.13/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "/private/var/folders/1b/6lfy9pzd0b58gbpvphcgmj6h0000gn/T/pip-build-env-dazivlui/overlay/lib/python3.13/site-packages/setuptools/_distutils/core.py", line 183, in setup
          return run_commands(dist)
        File "/private/var/folders/1b/6lfy9pzd0b58gbpvphcgmj6h0000gn/T/pip-build-env-dazivlui/overlay/lib/python3.13/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
          dist.run_commands()
          ~~~~~~~~~~~~~~~~~^^
        File "/private/var/folders/1b/6lfy9pzd0b58gbpvphcgmj6h0000gn/T/pip-build-env-dazivlui/overlay/lib/python3.13/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
          self.run_command(cmd)
          ~~~~~~~~~~~~~~~~^^^^^
        File "/private/var/folders/1b/6lfy9pzd0b58gbpvphcgmj6h0000gn/T/pip-build-env-dazivlui/overlay/lib/python3.13/site-packages/setuptools/dist.py", line 995, in run_command
          super().run_command(command)
          ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "/private/var/folders/1b/6lfy9pzd0b58gbpvphcgmj6h0000gn/T/pip-build-env-dazivlui/overlay/lib/python3.13/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
          ~~~~~~~~~~~^^
        File "/private/var/folders/1b/6lfy9pzd0b58gbpvphcgmj6h0000gn/T/pip-build-env-dazivlui/overlay/lib/python3.13/site-packages/setuptools/command/bdist_wheel.py", line 381, in run
          self.run_command("build")
          ~~~~~~~~~~~~~~~~^^^^^^^^^
        File "/private/var/folders/1b/6lfy9pzd0b58gbpvphcgmj6h0000gn/T/pip-build-env-dazivlui/overlay/lib/python3.13/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "/private/var/folders/1b/6lfy9pzd0b58gbpvphcgmj6h0000gn/T/pip-build-env-dazivlui/overlay/lib/python3.13/site-packages/setuptools/dist.py", line 995, in run_command
          super().run_command(command)
          ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "/private/var/folders/1b/6lfy9pzd0b58gbpvphcgmj6h0000gn/T/pip-build-env-dazivlui/overlay/lib/python3.13/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
          ~~~~~~~~~~~^^
        File "/private/var/folders/1b/6lfy9pzd0b58gbpvphcgmj6h0000gn/T/pip-build-env-dazivlui/overlay/lib/python3.13/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
          ~~~~~~~~~~~~~~~~^^^^^^^^^^
        File "/private/var/folders/1b/6lfy9pzd0b58gbpvphcgmj6h0000gn/T/pip-build-env-dazivlui/overlay/lib/python3.13/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "/private/var/folders/1b/6lfy9pzd0b58gbpvphcgmj6h0000gn/T/pip-build-env-dazivlui/overlay/lib/python3.13/site-packages/setuptools/dist.py", line 995, in run_command
          super().run_command(command)
          ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "/private/var/folders/1b/6lfy9pzd0b58gbpvphcgmj6h0000gn/T/pip-build-env-dazivlui/overlay/lib/python3.13/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
          ~~~~~~~~~~~^^
        File "/private/var/folders/1b/6lfy9pzd0b58gbpvphcgmj6h0000gn/T/pip-build-env-dazivlui/overlay/lib/python3.13/site-packages/setuptools/command/build_ext.py", line 99, in run
          _build_ext.run(self)
          ~~~~~~~~~~~~~~^^^^^^
        File "/private/var/folders/1b/6lfy9pzd0b58gbpvphcgmj6h0000gn/T/pip-build-env-dazivlui/overlay/lib/python3.13/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
          ~~~~~~~~~~~~~~~~~~~~~^^
        File "/private/var/folders/1b/6lfy9pzd0b58gbpvphcgmj6h0000gn/T/pip-build-env-dazivlui/overlay/lib/python3.13/site-packages/setuptools/_distutils/command/build_ext.py", line 476, in build_extensions
          self._build_extensions_serial()
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
        File "/private/var/folders/1b/6lfy9pzd0b58gbpvphcgmj6h0000gn/T/pip-build-env-dazivlui/overlay/lib/python3.13/site-packages/setuptools/_distutils/command/build_ext.py", line 502, in _build_extensions_serial
          self.build_extension(ext)
          ~~~~~~~~~~~~~~~~~~~~^^^^^
        File "<string>", line 87, in build_extension
        File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/subprocess.py", line 419, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['./build_bundled.sh', '0.2.0']' returned non-zero exit status 127.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for sentencepiece
Successfully built exo
Failed to build sentencepiece
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (sentencepiece)
```

Full Log:
```
source install.sh
The recommended version of Python to run exo with is Python 3.12, but Python 3.13.1 is installed. Proceeding with Python 3.13.1
Obtaining file:///Users/chriswong/Documents/repo/exo
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting tinygrad@ git+https://github.com/tinygrad/tinygrad.git@3b26e51fcebfc6576f4e0f99693e6f1406d61d79 (from exo==0.0.1)
  Using cached tinygrad-0.10.0-py3-none-any.whl
Collecting aiohttp==3.10.11 (from exo==0.0.1)
  Using cached aiohttp-3.10.11-cp313-cp313-macosx_11_0_arm64.whl.metadata (7.7 kB)
Collecting aiohttp_cors==0.7.0 (from exo==0.0.1)
  Using cached aiohttp_cors-0.7.0-py3-none-any.whl.metadata (20 kB)
Collecting aiofiles==24.1.0 (from exo==0.0.1)
  Using cached aiofiles-24.1.0-py3-none-any.whl.metadata (10 kB)
Collecting grpcio==1.68.0 (from exo==0.0.1)
  Using cached grpcio-1.68.0-cp313-cp313-macosx_10_13_universal2.whl.metadata (3.9 kB)
Collecting grpcio-tools==1.68.0 (from exo==0.0.1)
  Using cached grpcio_tools-1.68.0-cp313-cp313-macosx_10_13_universal2.whl.metadata (5.3 kB)
Collecting Jinja2==3.1.4 (from exo==0.0.1)
  Using cached jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
Collecting netifaces==0.11.0 (from exo==0.0.1)
  Using cached netifaces-0.11.0-cp313-cp313-macosx_10_13_universal2.whl
Collecting numpy==2.0.0 (from exo==0.0.1)
  Using cached numpy-2.0.0-cp313-cp313-macosx_15_0_arm64.whl
Collecting nuitka==2.5.1 (from exo==0.0.1)
  Using cached Nuitka-2.5.1-cp313-cp313-macosx_10_13_universal2.whl
Collecting nvidia-ml-py==12.560.30 (from exo==0.0.1)
  Using cached nvidia_ml_py-12.560.30-py3-none-any.whl.metadata (8.6 kB)
Collecting opencv-python==4.10.0.84 (from exo==0.0.1)
  Using cached opencv_python-4.10.0.84-cp37-abi3-macosx_11_0_arm64.whl.metadata (20 kB)
Collecting pillow==10.4.0 (from exo==0.0.1)
  Using cached pillow-10.4.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (9.2 kB)
Collecting prometheus-client==0.20.0 (from exo==0.0.1)
  Using cached prometheus_client-0.20.0-py3-none-any.whl.metadata (1.8 kB)
Collecting protobuf==5.28.1 (from exo==0.0.1)
  Using cached protobuf-5.28.1-cp38-abi3-macosx_10_9_universal2.whl.metadata (592 bytes)
Collecting psutil==6.0.0 (from exo==0.0.1)
  Using cached psutil-6.0.0-cp38-abi3-macosx_11_0_arm64.whl.metadata (21 kB)
Collecting pydantic==2.9.2 (from exo==0.0.1)
  Using cached pydantic-2.9.2-py3-none-any.whl.metadata (149 kB)
Collecting requests==2.32.3 (from exo==0.0.1)
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting rich==13.7.1 (from exo==0.0.1)
  Using cached rich-13.7.1-py3-none-any.whl.metadata (18 kB)
Collecting tenacity==9.0.0 (from exo==0.0.1)
  Using cached tenacity-9.0.0-py3-none-any.whl.metadata (1.2 kB)
Collecting tqdm==4.66.4 (from exo==0.0.1)
  Using cached tqdm-4.66.4-py3-none-any.whl.metadata (57 kB)
Collecting transformers==4.46.3 (from exo==0.0.1)
  Using cached transformers-4.46.3-py3-none-any.whl.metadata (44 kB)
Collecting uuid==1.30 (from exo==0.0.1)
  Using cached uuid-1.30-py3-none-any.whl
Collecting mlx==0.20.0 (from exo==0.0.1)
  Using cached mlx-0.20.0-cp313-cp313-macosx_14_0_arm64.whl.metadata (5.1 kB)
Collecting mlx-lm==0.19.3 (from exo==0.0.1)
  Using cached mlx_lm-0.19.3-py3-none-any.whl.metadata (8.9 kB)
Collecting aiohappyeyeballs>=2.3.0 (from aiohttp==3.10.11->exo==0.0.1)
  Using cached aiohappyeyeballs-2.4.4-py3-none-any.whl.metadata (6.1 kB)
Collecting aiosignal>=1.1.2 (from aiohttp==3.10.11->exo==0.0.1)
  Using cached aiosignal-1.3.1-py3-none-any.whl.metadata (4.0 kB)
Collecting attrs>=17.3.0 (from aiohttp==3.10.11->exo==0.0.1)
  Using cached attrs-24.2.0-py3-none-any.whl.metadata (11 kB)
Collecting frozenlist>=1.1.1 (from aiohttp==3.10.11->exo==0.0.1)
  Using cached frozenlist-1.5.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (13 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp==3.10.11->exo==0.0.1)
  Using cached multidict-6.1.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (5.0 kB)
Collecting yarl<2.0,>=1.12.0 (from aiohttp==3.10.11->exo==0.0.1)
  Using cached yarl-1.18.3-cp313-cp313-macosx_11_0_arm64.whl.metadata (69 kB)
Collecting setuptools (from grpcio-tools==1.68.0->exo==0.0.1)
  Using cached setuptools-75.6.0-py3-none-any.whl.metadata (6.7 kB)
Collecting MarkupSafe>=2.0 (from Jinja2==3.1.4->exo==0.0.1)
  Using cached MarkupSafe-3.0.2-cp313-cp313-macosx_11_0_arm64.whl.metadata (4.0 kB)
Collecting pyyaml (from mlx-lm==0.19.3->exo==0.0.1)
  Using cached PyYAML-6.0.2-cp313-cp313-macosx_11_0_arm64.whl.metadata (2.1 kB)
Collecting ordered-set>=4.1.0 (from nuitka==2.5.1->exo==0.0.1)
  Using cached ordered_set-4.1.0-py3-none-any.whl.metadata (5.3 kB)
Collecting zstandard>=0.15 (from nuitka==2.5.1->exo==0.0.1)
  Using cached zstandard-0.23.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (3.0 kB)
Collecting annotated-types>=0.6.0 (from pydantic==2.9.2->exo==0.0.1)
  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.23.4 (from pydantic==2.9.2->exo==0.0.1)
  Using cached pydantic_core-2.23.4-cp313-cp313-macosx_11_0_arm64.whl.metadata (6.6 kB)
Collecting typing-extensions>=4.12.2 (from pydantic==2.9.2->exo==0.0.1)
  Using cached typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Collecting charset-normalizer<4,>=2 (from requests==2.32.3->exo==0.0.1)
  Using cached charset_normalizer-3.4.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (34 kB)
Collecting idna<4,>=2.5 (from requests==2.32.3->exo==0.0.1)
  Using cached idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting urllib3<3,>=1.21.1 (from requests==2.32.3->exo==0.0.1)
  Using cached urllib3-2.2.3-py3-none-any.whl.metadata (6.5 kB)
Collecting certifi>=2017.4.17 (from requests==2.32.3->exo==0.0.1)
  Using cached certifi-2024.8.30-py3-none-any.whl.metadata (2.2 kB)
Collecting markdown-it-py>=2.2.0 (from rich==13.7.1->exo==0.0.1)
  Using cached markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)
Collecting pygments<3.0.0,>=2.13.0 (from rich==13.7.1->exo==0.0.1)
  Using cached pygments-2.18.0-py3-none-any.whl.metadata (2.5 kB)
Collecting filelock (from transformers==4.46.3->exo==0.0.1)
  Using cached filelock-3.16.1-py3-none-any.whl.metadata (2.9 kB)
Collecting huggingface-hub<1.0,>=0.23.2 (from transformers==4.46.3->exo==0.0.1)
  Using cached huggingface_hub-0.26.5-py3-none-any.whl.metadata (13 kB)
Collecting packaging>=20.0 (from transformers==4.46.3->exo==0.0.1)
  Using cached packaging-24.2-py3-none-any.whl.metadata (3.2 kB)
Collecting regex!=2019.12.17 (from transformers==4.46.3->exo==0.0.1)
  Using cached regex-2024.11.6-cp313-cp313-macosx_11_0_arm64.whl.metadata (40 kB)
Collecting tokenizers<0.21,>=0.20 (from transformers==4.46.3->exo==0.0.1)
  Using cached tokenizers-0.20.3-cp313-cp313-macosx_11_0_arm64.whl.metadata (6.7 kB)
Collecting safetensors>=0.4.1 (from transformers==4.46.3->exo==0.0.1)
  Using cached safetensors-0.4.5-cp313-cp313-macosx_11_0_arm64.whl.metadata (3.8 kB)
Collecting fsspec>=2023.5.0 (from huggingface-hub<1.0,>=0.23.2->transformers==4.46.3->exo==0.0.1)
  Using cached fsspec-2024.10.0-py3-none-any.whl.metadata (11 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich==13.7.1->exo==0.0.1)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Collecting sentencepiece!=0.1.92,>=0.1.91 (from transformers[sentencepiece]>=4.39.3->mlx-lm==0.19.3->exo==0.0.1)
  Using cached sentencepiece-0.2.0.tar.gz (2.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting propcache>=0.2.0 (from yarl<2.0,>=1.12.0->aiohttp==3.10.11->exo==0.0.1)
  Using cached propcache-0.2.1-cp313-cp313-macosx_11_0_arm64.whl.metadata (9.2 kB)
Using cached aiofiles-24.1.0-py3-none-any.whl (15 kB)
Using cached aiohttp-3.10.11-cp313-cp313-macosx_11_0_arm64.whl (388 kB)
Using cached aiohttp_cors-0.7.0-py3-none-any.whl (27 kB)
Using cached grpcio-1.68.0-cp313-cp313-macosx_10_13_universal2.whl (11.1 MB)
Using cached grpcio_tools-1.68.0-cp313-cp313-macosx_10_13_universal2.whl (5.6 MB)
Using cached jinja2-3.1.4-py3-none-any.whl (133 kB)
Using cached mlx-0.20.0-cp313-cp313-macosx_14_0_arm64.whl (23.5 MB)
Using cached mlx_lm-0.19.3-py3-none-any.whl (118 kB)
Using cached nvidia_ml_py-12.560.30-py3-none-any.whl (40 kB)
Using cached opencv_python-4.10.0.84-cp37-abi3-macosx_11_0_arm64.whl (54.8 MB)
Using cached pillow-10.4.0-cp313-cp313-macosx_11_0_arm64.whl (3.4 MB)
Using cached prometheus_client-0.20.0-py3-none-any.whl (54 kB)
Using cached protobuf-5.28.1-cp38-abi3-macosx_10_9_universal2.whl (414 kB)
Using cached psutil-6.0.0-cp38-abi3-macosx_11_0_arm64.whl (251 kB)
Using cached pydantic-2.9.2-py3-none-any.whl (434 kB)
Using cached requests-2.32.3-py3-none-any.whl (64 kB)
Using cached rich-13.7.1-py3-none-any.whl (240 kB)
Using cached tenacity-9.0.0-py3-none-any.whl (28 kB)
Using cached tqdm-4.66.4-py3-none-any.whl (78 kB)
Using cached transformers-4.46.3-py3-none-any.whl (10.0 MB)
Using cached pydantic_core-2.23.4-cp313-cp313-macosx_11_0_arm64.whl (1.8 MB)
Using cached aiohappyeyeballs-2.4.4-py3-none-any.whl (14 kB)
Using cached aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Using cached annotated_types-0.7.0-py3-none-any.whl (13 kB)
Using cached attrs-24.2.0-py3-none-any.whl (63 kB)
Using cached certifi-2024.8.30-py3-none-any.whl (167 kB)
Using cached charset_normalizer-3.4.0-cp313-cp313-macosx_11_0_arm64.whl (119 kB)
Using cached frozenlist-1.5.0-cp313-cp313-macosx_11_0_arm64.whl (50 kB)
Using cached huggingface_hub-0.26.5-py3-none-any.whl (447 kB)
Using cached idna-3.10-py3-none-any.whl (70 kB)
Using cached markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
Using cached MarkupSafe-3.0.2-cp313-cp313-macosx_11_0_arm64.whl (12 kB)
Using cached multidict-6.1.0-cp313-cp313-macosx_11_0_arm64.whl (29 kB)
Using cached ordered_set-4.1.0-py3-none-any.whl (7.6 kB)
Using cached packaging-24.2-py3-none-any.whl (65 kB)
Using cached pygments-2.18.0-py3-none-any.whl (1.2 MB)
Using cached PyYAML-6.0.2-cp313-cp313-macosx_11_0_arm64.whl (171 kB)
Using cached regex-2024.11.6-cp313-cp313-macosx_11_0_arm64.whl (284 kB)
Using cached safetensors-0.4.5-cp313-cp313-macosx_11_0_arm64.whl (382 kB)
Using cached tokenizers-0.20.3-cp313-cp313-macosx_11_0_arm64.whl (2.6 MB)
Using cached typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Using cached urllib3-2.2.3-py3-none-any.whl (126 kB)
Using cached yarl-1.18.3-cp313-cp313-macosx_11_0_arm64.whl (91 kB)
Using cached zstandard-0.23.0-cp313-cp313-macosx_11_0_arm64.whl (633 kB)
Using cached filelock-3.16.1-py3-none-any.whl (16 kB)
Using cached setuptools-75.6.0-py3-none-any.whl (1.2 MB)
Using cached fsspec-2024.10.0-py3-none-any.whl (179 kB)
Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Using cached propcache-0.2.1-cp313-cp313-macosx_11_0_arm64.whl (44 kB)
Building wheels for collected packages: exo, sentencepiece
  Building editable for exo (pyproject.toml) ... done
  Created wheel for exo: filename=exo-0.0.1-0.editable-py3-none-any.whl size=15497 sha256=dee8f03691838da17438f57d60bf270676648c4230d6aa65c72c3e5464254570
  Stored in directory: /private/var/folders/1b/6lfy9pzd0b58gbpvphcgmj6h0000gn/T/pip-ephem-wheel-cache-k6m4kfou/wheels/c1/5e/86/de3353864d7fe5f673e943bcb54e66446a47269a0283baa227
  Building wheel for sentencepiece (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for sentencepiece (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [106 lines of output]
      /private/var/folders/1b/6lfy9pzd0b58gbpvphcgmj6h0000gn/T/pip-build-env-dazivlui/overlay/lib/python3.13/site-packages/setuptools/_distutils/dist.py:261: UserWarning: Unknown distribution option: 'test_suite'
        warnings.warn(msg)
      running bdist_wheel
      running build
      running build_py
      creating build/lib.macosx-10.13-universal2-cpython-313/sentencepiece
      copying src/sentencepiece/__init__.py -> build/lib.macosx-10.13-universal2-cpython-313/sentencepiece
      copying src/sentencepiece/_version.py -> build/lib.macosx-10.13-universal2-cpython-313/sentencepiece
      copying src/sentencepiece/sentencepiece_model_pb2.py -> build/lib.macosx-10.13-universal2-cpython-313/sentencepiece
      copying src/sentencepiece/sentencepiece_pb2.py -> build/lib.macosx-10.13-universal2-cpython-313/sentencepiece
      running build_ext
      /bin/sh: pkg-config: command not found
      ./build_bundled.sh: line 21: cmake: command not found
      ./build_bundled.sh: line 22: nproc: command not found
      ./build_bundled.sh: line 22: cmake: command not found
      Traceback (most recent call last):
        File "/Users/chriswong/Documents/repo/exo/.venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "/Users/chriswong/Documents/repo/exo/.venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/chriswong/Documents/repo/exo/.venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                              metadata_directory)
                                              ^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/1b/6lfy9pzd0b58gbpvphcgmj6h0000gn/T/pip-build-env-dazivlui/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 438, in build_wheel
          return _build(['bdist_wheel', '--dist-info-dir', str(metadata_directory)])
        File "/private/var/folders/1b/6lfy9pzd0b58gbpvphcgmj6h0000gn/T/pip-build-env-dazivlui/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 426, in _build
          return self._build_with_temp_dir(
                 ~~~~~~~~~~~~~~~~~~~~~~~~~^
              cmd,
              ^^^^
          ...<3 lines>...
              self._arbitrary_args(config_settings),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          )
          ^
        File "/private/var/folders/1b/6lfy9pzd0b58gbpvphcgmj6h0000gn/T/pip-build-env-dazivlui/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 407, in _build_with_temp_dir
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/private/var/folders/1b/6lfy9pzd0b58gbpvphcgmj6h0000gn/T/pip-build-env-dazivlui/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/1b/6lfy9pzd0b58gbpvphcgmj6h0000gn/T/pip-build-env-dazivlui/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 169, in <module>
        File "/private/var/folders/1b/6lfy9pzd0b58gbpvphcgmj6h0000gn/T/pip-build-env-dazivlui/overlay/lib/python3.13/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "/private/var/folders/1b/6lfy9pzd0b58gbpvphcgmj6h0000gn/T/pip-build-env-dazivlui/overlay/lib/python3.13/site-packages/setuptools/_distutils/core.py", line 183, in setup
          return run_commands(dist)
        File "/private/var/folders/1b/6lfy9pzd0b58gbpvphcgmj6h0000gn/T/pip-build-env-dazivlui/overlay/lib/python3.13/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
          dist.run_commands()
          ~~~~~~~~~~~~~~~~~^^
        File "/private/var/folders/1b/6lfy9pzd0b58gbpvphcgmj6h0000gn/T/pip-build-env-dazivlui/overlay/lib/python3.13/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
          self.run_command(cmd)
          ~~~~~~~~~~~~~~~~^^^^^
        File "/private/var/folders/1b/6lfy9pzd0b58gbpvphcgmj6h0000gn/T/pip-build-env-dazivlui/overlay/lib/python3.13/site-packages/setuptools/dist.py", line 995, in run_command
          super().run_command(command)
          ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "/private/var/folders/1b/6lfy9pzd0b58gbpvphcgmj6h0000gn/T/pip-build-env-dazivlui/overlay/lib/python3.13/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
          ~~~~~~~~~~~^^
        File "/private/var/folders/1b/6lfy9pzd0b58gbpvphcgmj6h0000gn/T/pip-build-env-dazivlui/overlay/lib/python3.13/site-packages/setuptools/command/bdist_wheel.py", line 381, in run
          self.run_command("build")
          ~~~~~~~~~~~~~~~~^^^^^^^^^
        File "/private/var/folders/1b/6lfy9pzd0b58gbpvphcgmj6h0000gn/T/pip-build-env-dazivlui/overlay/lib/python3.13/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "/private/var/folders/1b/6lfy9pzd0b58gbpvphcgmj6h0000gn/T/pip-build-env-dazivlui/overlay/lib/python3.13/site-packages/setuptools/dist.py", line 995, in run_command
          super().run_command(command)
          ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "/private/var/folders/1b/6lfy9pzd0b58gbpvphcgmj6h0000gn/T/pip-build-env-dazivlui/overlay/lib/python3.13/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
          ~~~~~~~~~~~^^
        File "/private/var/folders/1b/6lfy9pzd0b58gbpvphcgmj6h0000gn/T/pip-build-env-dazivlui/overlay/lib/python3.13/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
          ~~~~~~~~~~~~~~~~^^^^^^^^^^
        File "/private/var/folders/1b/6lfy9pzd0b58gbpvphcgmj6h0000gn/T/pip-build-env-dazivlui/overlay/lib/python3.13/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "/private/var/folders/1b/6lfy9pzd0b58gbpvphcgmj6h0000gn/T/pip-build-env-dazivlui/overlay/lib/python3.13/site-packages/setuptools/dist.py", line 995, in run_command
          super().run_command(command)
          ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "/private/var/folders/1b/6lfy9pzd0b58gbpvphcgmj6h0000gn/T/pip-build-env-dazivlui/overlay/lib/python3.13/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
          ~~~~~~~~~~~^^
        File "/private/var/folders/1b/6lfy9pzd0b58gbpvphcgmj6h0000gn/T/pip-build-env-dazivlui/overlay/lib/python3.13/site-packages/setuptools/command/build_ext.py", line 99, in run
          _build_ext.run(self)
          ~~~~~~~~~~~~~~^^^^^^
        File "/private/var/folders/1b/6lfy9pzd0b58gbpvphcgmj6h0000gn/T/pip-build-env-dazivlui/overlay/lib/python3.13/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
          ~~~~~~~~~~~~~~~~~~~~~^^
        File "/private/var/folders/1b/6lfy9pzd0b58gbpvphcgmj6h0000gn/T/pip-build-env-dazivlui/overlay/lib/python3.13/site-packages/setuptools/_distutils/command/build_ext.py", line 476, in build_extensions
          self._build_extensions_serial()
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
        File "/private/var/folders/1b/6lfy9pzd0b58gbpvphcgmj6h0000gn/T/pip-build-env-dazivlui/overlay/lib/python3.13/site-packages/setuptools/_distutils/command/build_ext.py", line 502, in _build_extensions_serial
          self.build_extension(ext)
          ~~~~~~~~~~~~~~~~~~~~^^^^^
        File "<string>", line 87, in build_extension
        File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/subprocess.py", line 419, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['./build_bundled.sh', '0.2.0']' returned non-zero exit status 127.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for sentencepiece
Successfully built exo
Failed to build sentencepiece
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (sentencepiece)
```

**Comment by maruwtc** [comment]
I tried to run on a Windows desktop and also stuck at pyproject.toml

- OS: Windows 11 Pro 24H2
- CPU: i5-12600KF 
- RAM: 32 GB
- GPU: AMD Radeon RX 5700 XT

Error Log:
```
Collecting numpy==2.0.0 (from exo==0.0.1)
  Using cached numpy-2.0.0.tar.gz (18.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      + C:\Users\chriswong\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe C:\Users\chriswong\AppData\Local\Temp\pip-install-f_kherj6\numpy_9141455750004d39a5c21dcfc445f737\vendored-meson\meson\meson.py setup C:\Users\chriswong\AppData\Local\Temp\pip-install-f_kherj6\numpy_9141455750004d39a5c21dcfc445f737 C:\Users\chriswong\AppData\Local\Temp\pip-install-f_kherj6\numpy_9141455750004d39a5c21dcfc445f737\.mesonpy-mqfhq5jj -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=C:\Users\chriswong\AppData\Local\Temp\pip-install-f_kherj6\numpy_9141455750004d39a5c21dcfc445f737\.mesonpy-mqfhq5jj\meson-python-native-file.ini
      The Meson build system
      Version: 1.2.99
      Source dir: C:\Users\chriswong\AppData\Local\Temp\pip-install-f_kherj6\numpy_9141455750004d39a5c21dcfc445f737
      Build dir: C:\Users\chriswong\AppData\Local\Temp\pip-install-f_kherj6\numpy_9141455750004d39a5c21dcfc445f737\.mesonpy-mqfhq5jj
      Build type: native build
      Project name: NumPy
      Project version: 2.0.0
      WARNING: Failed to activate VS environment: Could not parse vswhere.exe output
     
      ..\meson.build:1:0: ERROR: Unknown compiler(s): [['icl'], ['cl'], ['cc'], ['gcc'], ['clang'], ['clang-cl'], ['pgcc']]
      The following exception(s) were encountered:
      Running `icl ""` gave "[WinError 2] The system cannot find the file specified"
      Running `cl /?` gave "[WinError 2] The system cannot find the file specified"
      Running `cc --version` gave "[WinError 2] The system cannot find the file specified"
      Running `gcc --version` gave "[WinError 2] The system cannot find the file specified"
      Running `clang --version` gave "[WinError 2] The system cannot find the file specified"
      Running `clang-cl /?` gave "[WinError 2] The system cannot find the file specified"
      Running `pgcc --version` gave "[WinError 2] The system cannot find the file specified"
     
      A full log can be found at C:\Users\chriswong\AppData\Local\Temp\pip-install-f_kherj6\numpy_9141455750004d39a5c21dcfc445f737\.mesonpy-mqfhq5jj\meson-logs\meson-log.txt
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Full log:
```
python3 -m pip install -e .
Defaulting to user installation because normal site-packages is not writeable
Obtaining file:///C:/Users/chriswong/Documents/Repo/exo
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting tinygrad@ git+https://github.com/tinygrad/tinygrad.git@3b26e51fcebfc6576f4e0f99693e6f1406d61d79 (from exo==0.0.1)
  Cloning https://github.com/tinygrad/tinygrad.git (to revision 3b26e51fcebfc6576f4e0f99693e6f1406d61d79) to c:\users\chriswong\appdata\local\temp\pip-install-f_kherj6\tinygrad_363cfb0e0db04c4aa28de373ae48b984
  Running command git clone --filter=blob:none --quiet https://github.com/tinygrad/tinygrad.git 'C:\Users\chriswong\AppData\Local\Temp\pip-install-f_kherj6\tinygrad_363cfb0e0db04c4aa28de373ae48b984'
  Running command git rev-parse -q --verify 'sha^3b26e51fcebfc6576f4e0f99693e6f1406d61d79'
  Running command git fetch -q https://github.com/tinygrad/tinygrad.git 3b26e51fcebfc6576f4e0f99693e6f1406d61d79
  Running command git checkout -q 3b26e51fcebfc6576f4e0f99693e6f1406d61d79
  Resolved https://github.com/tinygrad/tinygrad.git to commit 3b26e51fcebfc6576f4e0f99693e6f1406d61d79
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting aiohttp==3.10.11 (from exo==0.0.1)
  Using cached aiohttp-3.10.11-cp313-cp313-win_amd64.whl.metadata (8.0 kB)
Collecting aiohttp_cors==0.7.0 (from exo==0.0.1)
  Using cached aiohttp_cors-0.7.0-py3-none-any.whl.metadata (20 kB)
Collecting aiofiles==24.1.0 (from exo==0.0.1)
  Using cached aiofiles-24.1.0-py3-none-any.whl.metadata (10 kB)
Collecting grpcio==1.68.0 (from exo==0.0.1)
  Using cached grpcio-1.68.0-cp313-cp313-win_amd64.whl.metadata (4.0 kB)
Collecting grpcio-tools==1.68.0 (from exo==0.0.1)
  Using cached grpcio_tools-1.68.0-cp313-cp313-win_amd64.whl.metadata (5.5 kB)
Collecting Jinja2==3.1.4 (from exo==0.0.1)
  Using cached jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
Collecting netifaces==0.11.0 (from exo==0.0.1)
  Using cached netifaces-0.11.0.tar.gz (30 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy==2.0.0 (from exo==0.0.1)
  Using cached numpy-2.0.0.tar.gz (18.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      + C:\Users\chriswong\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe C:\Users\chriswong\AppData\Local\Temp\pip-install-f_kherj6\numpy_9141455750004d39a5c21dcfc445f737\vendored-meson\meson\meson.py setup C:\Users\chriswong\AppData\Local\Temp\pip-install-f_kherj6\numpy_9141455750004d39a5c21dcfc445f737 C:\Users\chriswong\AppData\Local\Temp\pip-install-f_kherj6\numpy_9141455750004d39a5c21dcfc445f737\.mesonpy-mqfhq5jj -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=C:\Users\chriswong\AppData\Local\Temp\pip-install-f_kherj6\numpy_9141455750004d39a5c21dcfc445f737\.mesonpy-mqfhq5jj\meson-python-native-file.ini
      The Meson build system
      Version: 1.2.99
      Source dir: C:\Users\chriswong\AppData\Local\Temp\pip-install-f_kherj6\numpy_9141455750004d39a5c21dcfc445f737
      Build dir: C:\Users\chriswong\AppData\Local\Temp\pip-install-f_kherj6\numpy_9141455750004d39a5c21dcfc445f737\.mesonpy-mqfhq5jj
      Build type: native build
      Project name: NumPy
      Project version: 2.0.0
      WARNING: Failed to activate VS environment: Could not parse vswhere.exe output
     
      ..\meson.build:1:0: ERROR: Unknown compiler(s): [['icl'], ['cl'], ['cc'], ['gcc'], ['clang'], ['clang-cl'], ['pgcc']]
      The following exception(s) were encountered:
      Running `icl ""` gave "[WinError 2] The system cannot find the file specified"
      Running `cl /?` gave "[WinError 2] The system cannot find the file specified"
      Running `cc --version` gave "[WinError 2] The system cannot find the file specified"
      Running `gcc --version` gave "[WinError 2] The system cannot find the file specified"
      Running `clang --version` gave "[WinError 2] The system cannot find the file specified"
      Running `clang-cl /?` gave "[WinError 2] The system cannot find the file specified"
      Running `pgcc --version` gave "[WinError 2] The system cannot find the file specified"
     
      A full log can be found at C:\Users\chriswong\AppData\Local\Temp\pip-install-f_kherj6\numpy_9141455750004d39a5c21dcfc445f737\.mesonpy-mqfhq5jj\meson-logs\meson-log.txt
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by OhJayGee** [comment]
Hi @maruwtc, on macOS you can fix the dependency error for sentencepiece by executing 
"brew install cmake" before you install exo.

**Comment by ThaddeusJiang** [comment]
> Hi [@maruwtc](https://github.com/maruwtc), on macOS you can fix the dependency error for sentencepiece by executing "brew install cmake" before you install exo.

Thank you @OhJayGee 

Fixed

**Comment by maruwtc** [comment]
> Hi [@maruwtc](https://github.com/maruwtc), on macOS you can fix the dependency error for sentencepiece by executing "brew install cmake" before you install exo.

Thank you @OhJayGee It's literally works for MacOS. However even I installed the cmake on Windows it's still not working. Do you have any idea on this?

**Comment by murflaw7424** [comment]
@maruwtc I received the same issue on Mac and Windows with WSL. I was able to get Windows to work with the following commands:

```
pip install -U pip setuptools wheel
pip install sentencepiece
pip install -e .
```

**Comment by Evanev7** [comment]
Should be fixed in 1.0
